### PR TITLE
Add 'Ignore nonreadable' to rsync module

### PR DESCRIPTION
**Pull request by jaggededgedjustice**

### CODE REVIEW

**Comment by igalic** [comment]
This is missing a documentation update.
Also, tests would be great!

**Comment by jaggededgedjustice** [comment]
The Readme has been updated. 
There's currently 1 test in spec/defines/server_module_spec.rb to ensure the setting is transfered into the config file. What other testing do you think would be useful?

**Comment by jcpunk** [comment]
+1 for this feature

**Comment by igalic** [comment]
this looks good to me, we just need someone to press the merge button.

**Pull request merged**
