### PR TITLE
Private exec

### PR DESCRIPTION
**Pull request by decibelhertz**
This PR addresses the same issue brought up in https://github.com/puppetlabs/puppetlabs-rsync/pull/45 and then some.

It also uses more functions to do input validation for `rsync::get` and `rsync::put` as well as makes a private type, `rsync::exec` that *put* and *get* are essentially wrapper for.

Rsync can also work with `rsync://` protocol, too.  So we should support that.  As the spec tests will now show, it also separates `$keyfile` and `$user`, since SSH does a better job of hunting for a user's key than a fixed, Linux-specific path as the default and we do not need to set *rsh* when using the *rsync* protocol.

### CODE REVIEW

**Comment by igalic** [comment]
nice! but now i'm thinking `rsync::exec` should be a type&provider pair :O

**Comment by decibelhertz** [comment]
That makes sense.  Let me see what I can do about that.

**Comment by decibelhertz** [comment]
Regarding the provider, are you thinking I call `Puppet::Util::Execution.execute` directly like `exec { }` does, or is there some cute way to have a provider create an exec resource directly that I'm missing?

**Comment by decibelhertz** [comment]
Regarding, the provider, what would you recommend?  Calling `Puppet::Util::Execution.execute` directly, or is there some cute way to invoke an `exec {}` resource in a provider that I've missed?

**Comment by igalic** [comment]
yes, `Puppet::Util::Execution.execute` is the way to go.

**Comment by decibelhertz** [comment]
Thanks; that's about what I figured.  Got the _type_ working well; I need a few spare cycles to get the _provider_ happy...

**Comment by mhaskel** [comment]
@decibelhertz thanks for the contribution! I like the idea of a type and provider instead of an exec define. Since that's going to be a completely different code base than this pull request I'm going to close this for now, but when you have the cycles to the type and provider working please submit a new pull request, because that sounds great :)

Also, feel free to ping me on #puppet-dev on freenode (my nick is _morgan) if you need any help. Thanks  again!

**Comment by decibelhertz** [comment]
Makes sense.  I'm 60% of the way there, but got waylaid with life.  I'll PR again when I have something.  Cheers.

**Pull request closed without merging**
