### PR TITLE
fix dependency for puppetlabs-xinetd

### PR DESCRIPTION
**Pull request by TheMeier**
test were failing with:
 (WARN) dependencies: Dependency puppetlabs/xinetd has an open ended dependency version requirement >=1.1.0

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @TheMeier. thanks for the PR. Can you please take a look at the used email address? It isn't associated with your github account.

**Comment by TheMeier** [comment]
Oops.... fixed :)

**Comment by TheMeier** [comment]
ping

**Comment by pmcmaw** [comment]
Closing as this is no longer an issue.

**Pull request closed without merging**
